- hosts: localhost
  collections:
  - community.aws
  tasks:
  - name: "Insatll Repo"
    shell: |
      sudo add-apt-repository -y ppa:deadsnakes/ppa
    become: yes
  - name: "Insatll packages"
    shell: |
      apt install -y software-properties-common python3.9 python3.9-distutils
    become: yes
  - name: "Change Python Version"
    shell: |
      update-alternatives --install /usr/bin/python python /usr/bin/python3.9 3
    become: yes
  - name: Get information about an instance
    rds_instance_info:
      db_instance_identifier: mydb
    register: new_database_info
  - name: "Create venv Python3.9"
    shell: |
      python3.9 -m venv /iac --without-pip
      curl https://bootstrap.pypa.io/get-pip.py | python3.9
    become: yes
  - name: "Config DB_HOST envvar"
    shell: |
      echo "DB_HOST={{ new_database_info.endpoint }}" >> /etc/environment
    become: yes
  - name: "Start Gunicorn"
    shell: |
      source /etc/environment
      gunicorn --chdir /iac --bind 0.0.0.0:8000 wsgi:app
    become: yes
